# Generated by Django 3.2.4 on 2021-10-01 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_initial'),
        ('scheduler', '0002_initial'),
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersetting',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist'),
        ),
        migrations.AlterField(
            model_name='computersetting',
            name='scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.scheduler'),
        ),
    ]
