# Generated by Django 3.2.4 on 2021-10-04 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_auto_20211001_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalcomputerdevice',
            old_name='clientele',
            new_name='user',
        ),
    ]
